In [1]:
import pandas as pd

file_path = r"C:\Users\Daksh Bhardwaj\anaconda3\Cleaned_Workforce_Dataset.xlsx"

df = pd.read_excel(file_path)

print("Shape:", df.shape)
print(df.head())

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nFirst 5 Rows:")
display(df.head())

Shape: (12500, 8)
       Emp_ID Department Location  Hire_Date      Status  Base_Salary_USD  \
0  EMP-000001         It   Remote 2017-05-26      Active          81429.0
1  EMP-000002         Hr   London 2018-02-07      Active          83596.0
2  EMP-000003    Finance   London 2020-11-03  Terminated          81143.0
3  EMP-000004         It   London 2022-12-11  Terminated         107047.0
4  EMP-000005    Support   Remote 2016-08-28      Active          95094.0

   Weekly_Capacity_Hrs  Performance_Rating
0                   40                   4
1                    0                   1
2                   40                   3
3                    0                   3
4                   40                   2

Columns:
['Emp_ID', 'Department', 'Location', 'Hire_Date', 'Status', 'Base_Salary_USD', 'Weekly_Capacity_Hrs', 'Performance_Rating']

Data Types:
Emp_ID                         object
Department                     object
Location                       object
Hire_Date              datetime64[ns]
Status                         object
Base_Salary_USD               float64
Weekly_Capacity_Hrs             int64
Performance_Rating              int64
dtype: object

Missing Values:
Emp_ID                 0
Department             0
Location               0
Hire_Date              0
Status                 0
Base_Salary_USD        0
Weekly_Capacity_Hrs    0
Performance_Rating     0
dtype: int64

First 5 Rows:

,Emp_ID,Department,Location,Hire_Date,Status,Base_Salary_USD,Weekly_Capacity_Hrs,Performance_Rating
0,EMP-000001,It,Remote,2017-05-26,Active,81429.0,40,4
1,EMP-000002,Hr,London,2018-02-07,Active,83596.0,0,1
2,EMP-000003,Finance,London,2020-11-03,Terminated,81143.0,40,3
3,EMP-000004,It,London,2022-12-11,Terminated,107047.0,0,3
4,EMP-000005,Support,Remote,2016-08-28,Active,95094.0,40,2

In [2]:
# Clean text columns
text_cols = ["Department", "Location", "Status"]

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

# Check the cleaned categories
print("Departments:")
print(df["Department"].unique())

print("\nLocations:")
print(df["Location"].unique())

print("\nStatuses:")
print(df["Status"].unique())

Departments:
['It' 'Hr' 'Finance' 'Support' 'Sales' 'Marketing']

Locations:
['Remote' 'London' 'San Francisco' 'Chicago' 'New York']

Statuses:
['Active' 'Terminated' 'On Leave']

In [3]:
missing = df.isnull().sum()

print("Missing values:")
print(missing)

print("\nMissing percentage:")
print((missing / len(df) * 100).round(2))

Missing values:
Emp_ID                 0
Department             0
Location               0
Hire_Date              0
Status                 0
Base_Salary_USD        0
Weekly_Capacity_Hrs    0
Performance_Rating     0
dtype: int64

Missing percentage:
Emp_ID                 0.0
Department             0.0
Location               0.0
Hire_Date              0.0
Status                 0.0
Base_Salary_USD        0.0
Weekly_Capacity_Hrs    0.0
Performance_Rating     0.0
dtype: float64

In [4]:
print("Rows with missing values:")
display(df[df.isnull().any(axis=1)].head(10))

Rows with missing values:

Empty DataFrame
Columns: [Emp_ID, Department, Location, Hire_Date, Status, Base_Salary_USD, Weekly_Capacity_Hrs, Performance_Rating]
Index: []

In [5]:
# Fill missing categorical values
df["Department"] = df["Department"].fillna("Unknown")
df["Location"] = df["Location"].fillna("Unknown")
df["Status"] = df["Status"].fillna("Unknown")

# Fill missing performance with median
df["Performance_Rating"] = df["Performance_Rating"].fillna(
    df["Performance_Rating"].median()
)

# Check remaining missing values
print(df.isnull().sum())

Emp_ID                 0
Department             0
Location               0
Hire_Date              0
Status                 0
Base_Salary_USD        0
Weekly_Capacity_Hrs    0
Performance_Rating     0
dtype: int64

In [6]:
print("Salary:")
print(df["Base_Salary_USD"].describe())

print("\nWeekly Capacity:")
print(df["Weekly_Capacity_Hrs"].describe())

print("\nPerformance Rating:")
print(df["Performance_Rating"].describe())

Salary:
count     12500.000000
mean      75066.708160
std       24397.288387
min          66.000000
25%       58817.250000
50%       74928.500000
75%       90880.000000
max      168196.000000
Name: Base_Salary_USD, dtype: float64

Weekly Capacity:
count    12500.000000
mean        35.379200
std          9.933182
min          0.000000
25%         40.000000
50%         40.000000
75%         40.000000
max         40.000000
Name: Weekly_Capacity_Hrs, dtype: float64

Performance Rating:
count    12500.000000
mean         3.225120
std          0.906304
min          1.000000
25%          3.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: Performance_Rating, dtype: float64

In [7]:
print("Negative salaries:")
display(df[df["Base_Salary_USD"] < 0])

print("Unusual capacity:")
display(df[df["Weekly_Capacity_Hrs"] > 80])

Negative salaries:

Empty DataFrame
Columns: [Emp_ID, Department, Location, Hire_Date, Status, Base_Salary_USD, Weekly_Capacity_Hrs, Performance_Rating]
Index: []

Unusual capacity:

Empty DataFrame
Columns: [Emp_ID, Department, Location, Hire_Date, Status, Base_Salary_USD, Weekly_Capacity_Hrs, Performance_Rating]
Index: []

In [8]:
# Mark invalid salary values as missing
df.loc[df["Base_Salary_USD"] < 0, "Base_Salary_USD"] = None

# Mark invalid capacity values as missing
df.loc[df["Weekly_Capacity_Hrs"] < 0, "Weekly_Capacity_Hrs"] = None
df.loc[df["Weekly_Capacity_Hrs"] > 80, "Weekly_Capacity_Hrs"] = None

# Fill with median values
df["Base_Salary_USD"] = df["Base_Salary_USD"].fillna(
    df["Base_Salary_USD"].median()
)

df["Weekly_Capacity_Hrs"] = df["Weekly_Capacity_Hrs"].fillna(
    df["Weekly_Capacity_Hrs"].median()
)

print(df[["Base_Salary_USD", "Weekly_Capacity_Hrs"]].describe())

       Base_Salary_USD  Weekly_Capacity_Hrs
count     12500.000000         12500.000000
mean      75066.708160            35.379200
std       24397.288387             9.933182
min          66.000000             0.000000
25%       58817.250000            40.000000
50%       74928.500000            40.000000
75%       90880.000000            40.000000
max      168196.000000            40.000000

In [9]:
print("Missing values:")
print(df.isnull().sum())

print("\nNegative salaries:")
print((df["Base_Salary_USD"] < 0).sum())

print("\nInvalid capacity:")
print(((df["Weekly_Capacity_Hrs"] < 0) |
       (df["Weekly_Capacity_Hrs"] > 80)).sum())

print("\nFinal shape:", df.shape)

Missing values:
Emp_ID                 0
Department             0
Location               0
Hire_Date              0
Status                 0
Base_Salary_USD        0
Weekly_Capacity_Hrs    0
Performance_Rating     0
dtype: int64

Negative salaries:
0

Invalid capacity:
0

Final shape: (12500, 8)

In [10]:
# Convert Hire_Date to datetime
df["Hire_Date"] = pd.to_datetime(
    df["Hire_Date"], errors="coerce"
)

# Check the result
print(df["Hire_Date"].dtype)

print("\nMissing Hire Dates:")
print(df["Hire_Date"].isnull().sum())

print("\nSample dates:")
print(df["Hire_Date"].head())

datetime64[ns]

Missing Hire Dates:
0

Sample dates:
0   2017-05-26
1   2018-02-07
2   2020-11-03
3   2022-12-11
4   2016-08-28
Name: Hire_Date, dtype: datetime64[ns]

In [11]:
print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nUnique Status:")
print(df["Status"].unique())

print("\nUnique Departments:")
print(df["Department"].unique())

Shape: (12500, 8)

Data Types:
Emp_ID                         object
Department                     object
Location                       object
Hire_Date              datetime64[ns]
Status                         object
Base_Salary_USD               float64
Weekly_Capacity_Hrs           float64
Performance_Rating              int64
dtype: object

Missing Values:
Emp_ID                 0
Department             0
Location               0
Hire_Date              0
Status                 0
Base_Salary_USD        0
Weekly_Capacity_Hrs    0
Performance_Rating     0
dtype: int64

Unique Status:
['Active' 'Terminated' 'On Leave']

Unique Departments:
['It' 'Hr' 'Finance' 'Support' 'Sales' 'Marketing']

In [15]:
output_path = r"D:\WORK - MAIN\PROJECTS\DAKSH\DAKSH PowerBI Projects\Dynamic Workforce & Hiring Planning Simulator\Cleaned_Workforce_Dataset.xlsx"

df.to_excel(output_path, index=False)

print("Final dataset saved successfully!")
print("Location:", output_path)
print("Rows:", len(df))
print("Columns:", len(df.columns))

Final dataset saved successfully!
Location: D:\WORK - MAIN\PROJECTS\DAKSH\DAKSH PowerBI Projects\Dynamic Workforce & Hiring Planning Simulator\Cleaned_Workforce_Dataset.xlsx
Rows: 12500
Columns: 8